### PR TITLE
Add project files created by Jetbrains IDEs to gitignore, plus vim temp files

### PR DESCRIPTION
**Pull request by eribeiro**

### CODE REVIEW

**Comment by dvanaken** [comment]
@eribeiro Can you update your branch?

**Comment by dvanaken** [comment]
@eribeiro if you update your branch then I will merge thanks

**Comment by edwardoliveira** [comment]
Hi Dana, sorry for the late response (been kind of offline past week or so). I am gonna update the branch, asap. Thanks! :)

**Comment by eribeiro** [comment]
Hi Dana, the conflicts were solved. Thanks! :)

**Pull request merged**
