### PR TITLE
Let GPR handle categorical variables (fixes #26)

### LINKED ISSUE #26: Encode categorical variables
When tuning knobs that are categorical variables (enums), OtterTune currently just replaces the enum with its index in the list of all possible enums. We need to add support to correctly handle categorical variables before running the machine learning algorithms by using an encoding scheme (e.g., dummy encoding, one-hot encoding).

### PR DESCRIPTION
**Pull request by swimj**
-- add hill-climbing method for selecting optimal categorical value within GPR gradient descent
-- simplified analysis/constraints.py code
-- added analysis/tests/test_contraints.py
-- simplified (and tested) dummy encoder's inverse_transform

### CODE REVIEW

**Comment by swimj** [comment]
This should be reviewed after #88

**Comment by bohanjason** [comment]
Could you please resolve conflicts first ?  We have changed asyn_tasks file, and you may want to update it. 

Also, can you merge the two PRs into a single PR ?

Thanks.

**Comment by swimj** [comment]
I made all the suggested fixes, let me know your thoughts!

@anyone more familiar with git -- not sure why GH is including everyone else's commits. I just rebased in order to fix some merge conflicts.

**Comment by bohanjason** [comment]
@swimj That's weird . Could you please push all your changes to your forked repo first, and  create a PR again. This PR seems to have all previous commits.

**Pull request closed without merging**
