### PR TITLE
Optimize get_tasks logic

### PR DESCRIPTION
**Pull request by eribeiro**
@bohanjason Why hitting Ottertune database with N queries (where N = number of task ids ) when you could use the idiom in this PR and then it will translate like _"SELECT ... FROM ... WHERE task_id IN (task_id1, task_id2, task_id3)"_

### CODE REVIEW

**Comment by bohanjason** [comment]
We need to show the task order correctly in the page view.  A list cannot guarantee the order

**Comment by edwardoliveira** [comment]
Yup, got it. But, out of curiosity, it wouldn't work even if you add an `order_by` after the `filter` call?

**Comment by eribeiro** [comment]
@bohanjason Yup, got it. But, out of curiosity, it wouldn't work even if you add an `order_by` after the `filter` call? Like

`TaskMeta.objects.filter(task_id__in=task_ids).order_by('task_id')` ??

The snippet above order the results by `task_id` in ascending order. Or `order_by('-task_id')` (minus sign before the property name to order in decreasing order.

And the `list()` call will preserve the order returned by TaskMeta, but materializing it from a `QuerySet`

What I am missing?

**Comment by eribeiro** [comment]
Oh, snap! Nevermind, I glossed over this sequence:

 https://github.com/cmu-db/ottertune/blob/7ee40961da8ec12f6b3a9aacd293c2cf2ca74892/server/website/website/views.py#L447

Deleting the feature branch.

**Pull request closed without merging**
