### PR TITLE
isolate workloads of different projects; extract workload merging process from recommandation

### PR DESCRIPTION
**Pull request by yangdsh**
The git lint will fail due to the added django migration file.

### CODE REVIEW

**Comment by dvanaken** [comment]
There are 8 errors in the unit tests too. Have you seen this?

**Comment by yangdsh** [comment]
> There are 8 errors in the unit tests too. Have you seen this?

Basically the fixture file for the website test lack the project field I just added. I am fixing this by generating a new fixture file.

**Comment by dvanaken** [comment]
You can add the new migration file to this config so the linter will skip it: https://github.com/cmu-db/ottertune/blob/master/script/formatting/config/pylintrc#L16

**Comment by yangdsh** [comment]
@dvanaken It is all set now. The only failure is due to the new migration file.

**Comment by yangdsh** [comment]
> You can add the new migration file to this config so the linter will skip it: https://github.com/cmu-db/ottertune/blob/master/script/formatting/config/pylintrc#L16

OK

**Comment by yangdsh** [comment]
@dvanaken Thank you! Now it is good to go! Yesterday I have run tests to verify that it did isolate the workloads from different projects, and my changes to the async_test did not break anything. Next, I plan to merge the DDPG recommendation pipeline with the GPR/DNN pipeline to make the code cleaner. However, if you have urgent things for me, I can do them first.

**Comment by dvanaken** [comment]
Awesome thanks @yangdsh

**Pull request merged**
