### PR TITLE
add dnn and gpr to simulation

### PR DESCRIPTION
**Pull request by yangdsh**
- simulator now supports dnn and gpr
- make it easier to run experiments in batch

### CODE REVIEW

**Comment by yangdsh** [comment]
Note that simulation.py is in style checker's white-list. However, I ran the style checker locally and fixed all style issues.

**Comment by yangdsh** [comment]
The following figure shows that ddpg out-performs dnn and gpr. However, there could be improvement space for dnn and gpr if we change their hyper-parameters. For now, I just copied the hyper-parameters from the setting/constants.py
[mode_0_knob_192.pdf](https://github.com/cmu-db/ottertune/files/3769468/mode_0_knob_192.pdf)
Another issue is that the training speed for dnn and gpr is almost 100 times slower than ddpg, which makes the overall experiments slow.
@bohanjason Could you please look into my simulation code for dnn and gpr to check if my implementation is correct and the hyper-parameters are reasonable? Thanks!

**Comment by dvanaken** [comment]
Actually that white list no longer exists because as of yesterday travis does not use source_validator.py. Now it uses the git-lint tool which uses the linter configs in script/formatter/config and only the default files/dirs have been added to it so far: https://github.com/cmu-db/ottertune/blob/master/script/formatting/config/pylintrc#L16

Looks like travis is having some issues: https://www.traviscistatus.com/

**Comment by dvanaken** [comment]
I just added the migrations directory to pylintrc so if the linter fails after travis runs then update you branch and it should be fixed (sorry I forgot to add it yesterday)

**Comment by yangdsh** [comment]
Hi @dvanaken , it seems that travis passed. What should I do now?

**Comment by dvanaken** [comment]
Wow GPR barely made any improvement at all. How many features are there and how many iterations did you run?

The hyperparameters look reasonable to me but let's see what Bohan thinks.

**Comment by bohanjason** [comment]
Nice work, Dongsheng!  The simulation is a good way to tune our models. Your DDPG results look good !

Let me tune NN and GPR models based on this environment and give you some preliminary results tomorrow. For GPR, I will increase sigma_multiplier to encourage exploration. We may change our default settings accordingly. 

Thanks.

**Comment by yangdsh** [comment]
This is for 192 knobs and 100 iterations in total.
I discussed with Bohan and Bohan will try new GPR and NN hyper-parameters and archetectures. Thanks!

**Pull request merged**
